# Generated by Django 4.2 on 2023-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_base',
            field=models.CharField(default='https://datalab-chatgpt.openai.azure.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_type',
            field=models.CharField(default='azure', max_length=10),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_version',
            field=models.CharField(default='2023-03-15-preview', max_length=10),
        ),
    ]
